# CC = gcc
CFLAGS = -Wall -g   
LDFLAGS =

all: assign3 

assign3: 
	gcc -Wall diskinfo.c -o diskinfo
	gcc -Wall disklist.c -o disklist
	gcc -Wall diskget.c -o diskget
	gcc -Wall diskput.c -o diskput


clean: 
	rm -rf *.o diskinfo disklist diskget diskput
